// API URL injected at extension download time by the server.
// Do not edit this file manually — it is replaced when you download
// the extension from /api/extension/download.
const API_URL = "__API_URL__";
