"""
Mindmap generation task - builds a tree structure from existing topics and subtopics.
Topics already have '>' separated hierarchies from split_topic_generation.
Subtopics are generated by subtopics_generation with parent_topic references.
"""
from lib.storage.submissions import SubmissionsStorage


def build_tree_from_topics(topics, subtopics):
    """
    Build a nested tree from topics (with '>' hierarchy) and subtopics.

    Args:
        topics: List of {name: "Cat>Sub>Leaf", sentences: [1, 2, 3]}
        subtopics: List of {name: "Detail", sentences: [1, 2], parent_topic: "Cat>Sub>Leaf"}

    Returns:
        Nested dict where each node has 'children' and 'sentences' keys.
    """
    tree = {}

    for topic in topics:
        name = topic.get("name", "")
        if not name or name == "no_topic":
            continue

        parts = [p.strip() for p in name.split(">") if p.strip()]
        sentences = topic.get("sentences", [])

        # Walk/create the path in the tree
        current = tree
        for part in parts:
            if part not in current:
                current[part] = {"children": {}, "sentences": []}
            # Propagate sentences to all ancestor levels
            existing = set(current[part]["sentences"])
            existing.update(sentences)
            current[part]["sentences"] = sorted(existing)
            current = current[part]["children"]

    # Attach subtopics as leaf children under their parent topic
    for subtopic in subtopics:
        parent_name = subtopic.get("parent_topic", "")
        sub_name = subtopic.get("name", "")
        sub_sentences = subtopic.get("sentences", [])

        if not parent_name or not sub_name or parent_name == "no_topic":
            continue

        parts = [p.strip() for p in parent_name.split(">") if p.strip()]

        # Navigate to the parent node
        current = tree
        found = True
        for part in parts:
            if part in current:
                current = current[part]["children"]
            else:
                found = False
                break

        if found:
            if sub_name not in current:
                current[sub_name] = {"children": {}, "sentences": []}
            existing = set(current[sub_name]["sentences"])
            existing.update(sub_sentences)
            current[sub_name]["sentences"] = sorted(existing)

    return tree


def process_mindmap(submission: dict, db, llm):
    """
    Process mindmap generation task for a submission.
    Builds tree from existing topics and subtopics - no LLM calls needed.

    Args:
        submission: Submission document from DB
        db: MongoDB database instance
        llm: LLamaCPP client instance (unused, kept for interface compatibility)
    """
    submission_id = submission["submission_id"]
    results = submission.get("results", {})

    sentences = results.get("sentences", [])
    topics = results.get("topics", [])
    subtopics = results.get("subtopics", [])

    if not topics or not sentences:
        raise ValueError("Topic extraction must be completed first")

    tree = build_tree_from_topics(topics, subtopics or [])

    # Update submission with results
    submissions_storage = SubmissionsStorage(db)
    submissions_storage.update_results(
        submission_id,
        {
            "topic_mindmaps": tree,
        }
    )

    print(f"Mindmap generation completed for submission {submission_id}: "
          f"{len(topics)} topics, {len(subtopics or [])} subtopics")
