import logging
import uuid
from datetime import UTC, datetime
from typing import Any, List, Optional

from pymongo import ReturnDocument
from pymongo.database import Database


class CanvasChatsStorage:
    """Storage for canvas chat sessions.

    Each chat session is scoped to a single article and stores its own
    conversation messages and the events (e.g. highlight_span) that were
    generated by the LLM within the context of that chat.

    Document shape::

        {
            "chat_id": str,           # uuid hex, unique per chat
            "article_id": str,        # parent article submission_id
            "title": str,             # short title (first user message)
            "created_at": datetime,
            "updated_at": datetime,
            "messages": [             # full conversation history
                {"role": "user"|"assistant", "content": str, "ts": datetime}
            ],
            "events": [               # events generated within this chat
                {
                    "seq": int,       # 1-based, unique per chat
                    "event_type": str,
                    "data": dict,
                    "created_at": datetime,
                }
            ],
            "event_seq": int,         # last assigned event seq
        }
    """

    indexes: List[str] = ["article_id", "chat_id"]

    def __init__(self, db: Database) -> None:
        self._db: Database = db
        self._log = logging.getLogger("canvas_chats")

    def prepare(self) -> None:
        for index in self.indexes:
            try:
                self._db.canvas_chats.create_index(index)
            except Exception as e:
                self._log.warning(
                    "Can't create index %s. May be already exists. Info: %s", index, e
                )
        try:
            self._db.canvas_chats.create_index("chat_id", unique=True)
        except Exception as e:
            self._log.warning("Can't create unique index on chat_id. Info: %s", e)

    # ── Chat CRUD ─────────────────────────────────────────────────────────

    def create_chat(
        self, article_id: str, title: Optional[str] = None
    ) -> dict[str, Any]:
        now = datetime.now(UTC)
        chat: dict[str, Any] = {
            "chat_id": uuid.uuid4().hex,
            "article_id": article_id,
            "title": title or "New chat",
            "created_at": now,
            "updated_at": now,
            "messages": [],
            "events": [],
            "event_seq": 0,
        }
        self._db.canvas_chats.insert_one(chat)
        chat["_id"] = str(chat["_id"])
        return chat

    def list_chats(self, article_id: str) -> List[dict[str, Any]]:
        cursor = self._db.canvas_chats.find(
            {"article_id": article_id},
            projection={
                "chat_id": 1,
                "article_id": 1,
                "title": 1,
                "created_at": 1,
                "updated_at": 1,
                "messages": 1,
                "events": 1,
            },
        ).sort("updated_at", -1)

        result: List[dict[str, Any]] = []
        for doc in cursor:
            doc["_id"] = str(doc["_id"])
            doc["message_count"] = len(doc.get("messages") or [])
            doc["event_count"] = len(doc.get("events") or [])
            # Drop heavy fields from the listing payload.
            doc.pop("messages", None)
            doc.pop("events", None)
            result.append(doc)
        return result

    def get_chat(self, article_id: str, chat_id: str) -> Optional[dict[str, Any]]:
        doc = self._db.canvas_chats.find_one(
            {"article_id": article_id, "chat_id": chat_id}
        )
        if not doc:
            return None
        doc["_id"] = str(doc["_id"])
        return doc

    def delete_chat(self, article_id: str, chat_id: str) -> bool:
        result = self._db.canvas_chats.delete_one(
            {"article_id": article_id, "chat_id": chat_id}
        )
        return result.deleted_count > 0

    def update_title(self, article_id: str, chat_id: str, title: str) -> bool:
        now = datetime.now(UTC)
        result = self._db.canvas_chats.update_one(
            {"article_id": article_id, "chat_id": chat_id},
            {"$set": {"title": title, "updated_at": now}},
        )
        return result.modified_count > 0

    # ── Messages ──────────────────────────────────────────────────────────

    def add_message(
        self, article_id: str, chat_id: str, role: str, content: str
    ) -> bool:
        now = datetime.now(UTC)
        message = {"role": role, "content": content, "ts": now}
        update: dict[str, Any] = {
            "$push": {"messages": message},
            "$set": {"updated_at": now},
        }
        # If this is the first user message, also set title from it.
        result = self._db.canvas_chats.update_one(
            {"article_id": article_id, "chat_id": chat_id},
            update,
        )
        if result.modified_count and role == "user":
            self._maybe_set_title_from_first_message(article_id, chat_id)
        return result.modified_count > 0

    def _maybe_set_title_from_first_message(
        self, article_id: str, chat_id: str
    ) -> None:
        doc = self._db.canvas_chats.find_one(
            {"article_id": article_id, "chat_id": chat_id},
            projection={"title": 1, "messages": 1},
        )
        if not doc:
            return
        title = (doc.get("title") or "").strip()
        if title and title != "New chat":
            return
        messages = doc.get("messages") or []
        first_user = next((m for m in messages if m.get("role") == "user"), None)
        if not first_user:
            return
        new_title = (first_user.get("content") or "").strip()
        if not new_title:
            return
        if len(new_title) > 60:
            new_title = new_title[:57].rstrip() + "..."
        self._db.canvas_chats.update_one(
            {"article_id": article_id, "chat_id": chat_id},
            {"$set": {"title": new_title}},
        )

    # ── Events embedded in chat ───────────────────────────────────────────

    def add_event(
        self,
        article_id: str,
        chat_id: str,
        event_type: str,
        data: dict[str, Any],
    ) -> Optional[dict[str, Any]]:
        now = datetime.now(UTC)
        doc = self._db.canvas_chats.find_one_and_update(
            {"article_id": article_id, "chat_id": chat_id},
            {"$inc": {"event_seq": 1}, "$set": {"updated_at": now}},
            return_document=ReturnDocument.AFTER,
            projection={"event_seq": 1},
        )
        if not doc:
            return None
        seq = int(doc["event_seq"])
        event: dict[str, Any] = {
            "seq": seq,
            "event_type": event_type,
            "data": data,
            "created_at": now,
        }
        self._db.canvas_chats.update_one(
            {"article_id": article_id, "chat_id": chat_id},
            {"$push": {"events": event}},
        )
        return event

    def get_events(
        self,
        article_id: str,
        chat_id: str,
        offset: int = 0,
        limit: int = 50,
    ) -> List[dict[str, Any]]:
        doc = self._db.canvas_chats.find_one(
            {"article_id": article_id, "chat_id": chat_id},
            projection={"events": 1},
        )
        if not doc:
            return []
        events = list(doc.get("events") or [])
        events.sort(key=lambda e: e.get("seq", 0))
        if offset:
            events = events[offset:]
        if limit:
            events = events[:limit]
        return events

    def delete_event(self, article_id: str, chat_id: str, seq: int) -> bool:
        now = datetime.now(UTC)
        result = self._db.canvas_chats.update_one(
            {"article_id": article_id, "chat_id": chat_id},
            {
                "$pull": {"events": {"seq": seq}},
                "$set": {"updated_at": now},
            },
        )
        return result.modified_count > 0
